/*
 Johannes Schneemann
 November 26, 2019
 
 *****************************************************
 This C program compares the performance of the LRU
 and the Optimal page replacement algorithms.
 *****************************************************
 
 Description:
 The program will take a reference string and the number of frames as inputs.
 The maximum length of a reference string is 20 and there are 5 diffent pages from
 page 1 to page 5. The reference string can be randomly generated and the number of
 frames (max. 5) is entered through the keyboard. For example, the system generates a reference
 string 2 1 3 4 5 2 3 ...5 and you enter the number of frames 3.
 Compare the number of page faults generated by the Optimal and LRU algorithms.
 Print out the page replacement process and you can see
 how LRU differs from the optimal.
 Note: Ties are not addressed!
*/

#include <stdlib.h>
#include <stdio.h>
#include <time.h>

int inMemory(int reference, int memory[], int numberFrames);
void displayMemory(int memory[], int numberFrames);
int min(int a, int b);
int max(int a, int b);
int pageFaults = 0;

int main(){
    int numberFrames = -1, refStringLength = -1;
    int memory[5], referenceString[20];

    for(;;){
        printf("Please enter the length of the reference string (max 20):");
        scanf(" %d", &refStringLength);

        printf("Please enter the number of frames to use (max 5):");
        scanf(" %d", &numberFrames);
        
        if(refStringLength >= 1 && refStringLength <= 20 &&
           numberFrames >= 1 && numberFrames <= 5){
            srand(time(NULL));
            
            //initialize all frames to zero
            for(int i = 0; i < numberFrames; i++){
                memory[i] = 0;
            }

            //random reference string
            for(int i = 0; i < refStringLength; i++){
                int randInt = ((rand() % 5) + 1);
                if(randInt != referenceString[i - 1]){
                    referenceString[i] = randInt;
                }else{
                    i--;
                }
            }

            if(refStringLength != 20){
                referenceString[refStringLength] = -1;
            }
            
            //Display reference string
            printf("\nThe generated reference string is:\n");
            int i = 0;
            while((referenceString[i] != -1) && (i < 20)){
                printf("%d ", referenceString[i]);
                i++;
            }
            printf("\n");
            
            /*
             *  Optimal Algorithm
             */
            printf("\n<----------*** OPTIMAL ALRORITHM ***---------->\n");
            /*  If there is an empty frame & reference is not in the list,
            *   load a page into it. Variable i iterates through the frames
            *   and variable j iterates through the reference string.
            */
            i = 0;
            int j = 0;
            for(j = 0; i < numberFrames; j++){
                if(referenceString[j] == -1){
                    break;
                }else if(!inMemory(referenceString[j], memory, numberFrames)){
                    memory[i] = referenceString[j];
                    i++;
                    displayMemory(memory, numberFrames);
                }else{
                    printf("%d Page found in memory.\n", referenceString[j]);
                }
            }
            while(j < refStringLength){
                int out = 0;
                if(inMemory(referenceString[j], memory, numberFrames)){
                    printf("%d found in memory.\n", referenceString[j]);
                }else{
                    /*
                     *  Page replacement section for Optimal
                     */
                   
            }
            printf("NUMBER OF PAGE FAULTS: %d\n", pageFaults);

            /*
            *  LRU Algorithm
            */
            printf("\n<----------*** LRU ALRORITHM ***---------->\n");
            /*  If there is an empty frame & reference is not in the list,
            *   load a page into it. Variable i iterates through the frames
            *   and variable j iterates through the reference string.
            */

            //initialize all frames to zero and reset page fault counter
            for(int i = 0; i < numberFrames; i++)
                memory[i] = 0;
            pageFaults = 0;
            i = 0;
            j = 0;
            
            for(j = 0; i < numberFrames; j++){
                if(referenceString[j] == -1)
                    break;
                else if(!inMemory(referenceString[j], memory, numberFrames)){
                    memory[i] = referenceString[j];
                    i++;
                    displayMemory(memory, numberFrames);
                }else{
                    printf("%d is in memory.\n", referenceString[j]);
                }
            }
            while(j < refStringLength){
                int _replacementIndex;
                int _out;
                if(inMemory(referenceString[j], memory, numberFrames)){
                    printf("%d is in memory.\n", referenceString[j]);
                }else{
                    /*
                     *      Page replacement section for LRU
                     *  Move from the end to get LRU and determines
                     *  LRU by getting most previous reference string call
                     */
                   
            }
            printf("NUMBER OF PAGE FAULTS: %d\n\n", pageFaults);
            break;
        }
        printf("Invalid selection, choose again.\n");
    }
    return 0;
}

int inMemory(int reference, int memory[], int numberFrames){
   
}

void displayMemory(int memory[], int numberFrames){
    
}

int min(int a, int b){
    if(a < b)
        return a;
    return b;
}

int max(int a, int b){
    if(a > b)
        return a;
    return b;
}


